# Generated by Django 5.0.7 on 2024-08-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='salePrice',
            new_name='sale_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='totalQuantity',
            new_name='total_quantity',
        ),
    ]
