# Generated by Django 5.0.4 on 2024-08-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='sale/published_products')),
                ('product_type', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('publish_price', models.CharField(max_length=300)),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
            ],
        ),
    ]
